import { useState } from 'react'
import Head from 'next/head'
import { Textarea, Box, Text, Input } from '@chakra-ui/react'
import arrayToChunks from '../utils/arrayToChunks'

const encryptMessage = (message, key) => {
  const keyLength = key.length
  const keyLetters = key.split('').map(l => l.toLowerCase())
  const messageLetters = message.split('') 
  const chunkedMessage = arrayToChunks(messageLetters, keyLength)
  const messageGrid = [keyLetters, ...chunkedMessage]
  const sortedLetters = keyLetters.sort()
  for(let i = 0 ; i < sortedLetters.length; i++){

  }
  return messageGrid
}

export default function Home() {
  const [values, setValues] = useState({
    message: '',
    key: ''
  })
  const encryptedMsg = encryptMessage(values.message, values.key)
  const handleInputChange = (e) => {
    const { value, name } = e.target
    setValues(prevValues => ({ ...prevValues, [name]: value }))
  }

  

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Box>
        <Text mb='8px'>{''+encryptedMsg}</Text>
        <Textarea
          value={values.message}
          onChange={handleInputChange}
          name='message'
          placeholder='Enter your message'
        />
        <Input
          value={values.key}
          onChange={handleInputChange}
          name="key"
          placeholder='Enter your key'
          />
      </Box>
    </div>
  )
}
